spring:
  profiles:
    active: dev
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 2048
dwsurvey:
  # 产品版本号信息，V5-代表最新的前后端分离版本，vue+jquery; v6 版本纯vue实现
  version:
    api: https://www.surveyform.cn
    name: 社区版
    name-code: OSS
    built: 20250211
    code: V6.14.0
    # OSS-V6.11-241118
    number: ${dwsurvey.version.name-code}-${dwsurvey.version.code}-${dwsurvey.version.built}
    # DWSurvey-OSS-V6.11-241118
    info: DWSurvey-${dwsurvey.version.number}



